### ISSUE TITLE
HELP PLS

### ISSUE THREAD

**Issue by Mario2280** [nlynzaad/nestjs_graphql_generic_resolver#1]
@nlynzaad Hello, sorry to open a issue. This is just a way to contact you. I had a problem in a project similar to yours when using the generated names query and mutation I get an error

```
\node_modules\@nestjs\graphql\dist\utils\reflection.utilts.js:17
            throw new undefined_type_error_1.UndefinedTypeError((0, lodash_1.get)(prototype, 'constructor.name'), 
propertyKey, index);
                  ^
Error: Undefined type error. Make sure you are providing 
an explicit type for the "findFirst" (parameter at index 
[0]) of the "BaseResolverHost" class.
    at reflectTypeFromMetadata (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\utils\reflection.utilts.js:17:19)
    at E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\decorators\args.decorator.js:22:106
    at singleCallFunctionWrapper (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\schema-builder\storages\lazy-metadata.storage.js:67:13)
    at E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\schema-builder\storages\lazy-metadata.storage.js:41:44 
    at Array.forEach (<anonymous>)
    at LazyMetadataStorageHost.load (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\schema-builder\storages\lazy-metadata.storage.js:41:26)
    at GraphQLSchemaFactory.create (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\schema-builder\graphql-schema.factory.js:35:53)
    at GraphQLSchemaBuilder.generateSchema (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\graphql-schema.builder.js:35:52)
    at GraphQLSchemaBuilder.build (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\graphql-schema.builder.js:22:31)
    at GraphQLFactory.generateSchema (E:\Work\tapply-be\node_modules\@nestjs\graphql\dist\graphql.factory.js:27:69)
```
I dont know why this is is not work

This is my code:
```
import { Args, Mutation, Query, Resolver } from '@nestjs/graphql'
import { IBaseCrudeService } from './basic-crud.service'
import { AffectedRows } from 'src/dtos'
import { Injectable } from '@nestjs/common'

type Constructor<I> = new (...args: any[]) => I // Main Point

export function BaseResolver<
  T,
  FindFirstArgs,
  FindUniqueArgs,
  CreateOneArgs,
  CreateManyArgs,
  DeleteManyArgs,
  DeleteOneArgs,
  FindManyArgs,
  UpdateOneArgs,
  UpdateManyArgs,
  AggregateArgs,
  GroupByArgs,
>(classRef: Constructor<T>, GroupBy, Aggregate): any {
  @Injectable()
  @Resolver({ isAbstract: true })
  abstract class BaseResolverHost {
    modelName: string
    constructor(private readonly service: IBaseCrudeService) {
      this.modelName = this.getModelName()
    }

    private getModelName(): string {
      return this.constructor.name.replace('Resolver', '')
    }
    //METADATA ERROR HERE SOLUTION https://github.com/nlynzaad/nestjs_graphql_generic_resolver/blob/main/src/base/base.resolver.ts
    //NEED TO FIND WHAT IS DIFFERENT
    @Query(() => classRef, {
      nullable: true,
      name: `findFirst${classRef.name}`,
    })
    findFirst(@Args() args: FindFirstArgs) {
      this.service.findFirst(args)
    }

    @Query(() => classRef, {
      nullable: true,
      name: `findUnique${classRef.name}`,
    })
    findUnique(@Args() args: FindUniqueArgs) {
      return this.service.findUnique(args)
    }

    @Query(() => [classRef], {
      nullable: false,
      name: `lists${classRef.name}`,
    })
    lists(@Args() args: FindManyArgs) {
      return this.service.findMany(args)
    }

    @Query(() => [GroupBy], {
      nullable: false,
      name: `groupBy${classRef.name}`,
    })
    groupBy(@Args() args: GroupByArgs) {
      return this.service.groupBy(args)
    }

    @Query(() => Aggregate, {
      nullable: false,
      name: `aggregate${classRef.name}`,
    })
    aggregate(@Args() args: AggregateArgs) {
      return this.service.aggregate(args)
    }

    @Mutation(() => classRef, {
      nullable: true,
      name: `create${classRef.name}`,
    })
    create(@Args() args: CreateOneArgs) {
      return this.service.create(args)
    }

    @Mutation(() => AffectedRows, {
      nullable: true,
      name: `createMany${classRef.name}`,
    })
    createMany(@Args() args: CreateManyArgs) {
      return this.service.createMany(args)
    }

    @Mutation(() => classRef, {
      nullable: true,
      name: `update${classRef.name}`,
    })
    update(@Args() args: UpdateOneArgs) {
      return this.service.update(args)
    }

    @Mutation(() => AffectedRows, {
      nullable: true,
      name: `updateMany${classRef.name}`,
    })
    updateMany(@Args() args: UpdateManyArgs) {
      return this.service.updateMany(args)
    }

    @Mutation(() => classRef, {
      nullable: true,
      name: `delete${classRef.name}`,
    })
    delete(@Args() args: DeleteOneArgs) {
      return this.service.delete(args)
    }

    @Mutation(() => AffectedRows, {
      nullable: true,
      name: `deleteMany${classRef.name}`,
    })
    deleteMany(@Args() args: DeleteManyArgs) {
      return this.service.deleteMany(args)
    }
  }
  return BaseResolverHost
}
```
```
import {
  UserGroupBy,
  User,
  AggregateUser,
  FindFirstUserArgs,
  FindUniqueUserArgs,
  CreateOneUserArgs,
  CreateManyUserArgs,
  DeleteManyUserArgs,
  DeleteOneUserArgs,
  FindManyUserArgs,
  UpdateOneUserArgs,
  UpdateManyUserArgs,
  UserAggregateArgs,
  UserGroupByArgs,
} from '../dtos/index'
import { BaseResolver } from 'src/shared/TODObasic-crud.resolver'

//TODO SEE src\shared\TODObasic-crud.resolver.ts
@Resolver(() => User)
export class UserResolver extends BaseResolver<
  User,
  FindFirstUserArgs,
  FindUniqueUserArgs,
  CreateOneUserArgs,
  CreateManyUserArgs,
  DeleteManyUserArgs,
  DeleteOneUserArgs,
  FindManyUserArgs,
  UpdateOneUserArgs,
  UpdateManyUserArgs,
  UserAggregateArgs,
  UserGroupByArgs
>(User, UserGroupBy, AggregateUser) {
  constructor(private readonly userService: UserService) {
    super(userService)
  }
}
```
I have the same code as you just different packages how did you get it to work?

**Comment by nlynzaad** [comment]
Hi,

I unfortunately only dabbled with Nest when I wrote this and since then haven't looked at it again.

However looking at your error it seems to be related to the type inference not resolving clearly enough for the graphql schema. The main difference I could see between your example and mine is I provided generic typing to my base service, i.e. the resultant output in the base service and the base resolver is always <T>. I honestly can't recall much of this but I'm guessing this should help dictate the type more explicitly that is returned by the service when called from the resolver.
